apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akslabshanito-9016"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akslabshanito-9016"
  template:
    metadata:
      labels:
        app: "akslabshanito-9016"
    spec:
      containers:
        - name: "akslabshanito-9016"
          image: "acrdemo1207.azurecr.io/akslabshanito"
          ports:
          - containerPort: 80